repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: full test
        name: full test
        entry: devbox run test
        language: system
        stages: [pre-push]
        pass_filenames: false
      - id: biome format
        name: biome format
        entry: devbox run -- bunx biome check --write --no-errors-on-unmatched
        language: system
        files: \.(js|jsx|ts|tsx|css|json|html|svg)$
        stages: [pre-commit]
        pass_filenames: true
